export const ATTRIBUTES_TYPES = {
  STRING: 'STRING',
  OBJECT: 'OBJECT',
};

export const ATTRIBUTES_STRING_FORMATS = {
  NONE: 'NONE',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  DATETIME: 'DATETIME',
  CDATA: 'CDATA',
  URI: 'URI',
};
