export const ACTIONS = {

  // Fields
  FIELDS_ADD: 'FIELDS_ADD',
  FIELDS_SAVE: 'FIELDS_SAVE',
  FIELDS_MOVE: 'FIELDS_MOVE',
  FIELDS_REMOVE: 'FIELDS_REMOVE',

  // Categories
  CATS_FETCHING: 'CATS_FETCHING',
  CATS_SAVE: 'CATS_SAVE',
};

export const TYPES = {
  STRING: 'STRING',
  OBJECT: 'OBJECT',
};

export const FORMATS = {
  NONE: '',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  DATETIME: 'DATETIME',
  CDATA: 'CDATA',
  URI: 'URI',
};
